"""Routes for opening local V2 artifact outputs in the browser."""

from __future__ import annotations

import mimetypes
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse

router = APIRouter(tags=["v2-artifacts"])

_ALLOWED_SUFFIXES = {
    ".html",
    ".htm",
    ".tif",
    ".tiff",
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
    ".json",
    ".txt",
    ".md",
    ".csv",
    ".pkl",
}
_ALLOWED_ROOTS = (Path("/tmp"), Path.home())


@router.get(
    "/v2/artifacts/open",
    summary="Open a local artifact generated by the V2 runtime",
)
async def open_v2_artifact(
    path: str = Query(..., description="Absolute local artifact path generated by the runtime."),
) -> FileResponse:
    candidate = Path(path.removeprefix("file://")).expanduser().resolve()
    if not candidate.is_absolute():
        raise HTTPException(status_code=400, detail="artifact_path_must_be_absolute")
    if not any(candidate.is_relative_to(root) for root in _ALLOWED_ROOTS):
        raise HTTPException(status_code=403, detail="artifact_path_not_allowed")
    if candidate.suffix.lower() not in _ALLOWED_SUFFIXES:
        raise HTTPException(status_code=400, detail="artifact_suffix_not_allowed")
    if not candidate.exists() or not candidate.is_file():
        raise HTTPException(status_code=404, detail="artifact_not_found")
    media_type, _ = mimetypes.guess_type(str(candidate))
    return FileResponse(path=str(candidate), media_type=media_type)
